module.exports = {
  game: [
    {
      id: "1",
      week: "5",
      team1: "Tennessee Titans",
      team2: "New Orleans Saints",
      team1Spread: 3.5,
      team2Spread: -3.5,
      team1Url: "https://wagerwire-webassets.s3.amazonaws.com/titans.png",
      team2Url: "https://wagerwire-webassets.s3.amazonaws.com/saints.png",
      date: "Thursday @ 1:00pm",
    },
    {
      id: "2",
      week: "5",
      team1: "Detroit Lions",
      team2: "Kansas City Chiefs",
      team1Spread: 6.5,
      team2Spread: -6.5,
      team1Url: "https://wagerwire-webassets.s3.amazonaws.com/lions.png",
      team2Url: "https://wagerwire-webassets.s3.amazonaws.com/chiefs.png",
      date: "Thursday @ 8:20pm",
    },
    {
      id: "3",
      week: "5",
      team1: "Cincinnati Bengals",
      team2: "Cleveland Browns",
      team1Spread: -9.5,
      team2Spread: 9.5,
      team1Url: "https://wagerwire-webassets.s3.amazonaws.com/bengals.png",
      team2Url: "https://wagerwire-webassets.s3.amazonaws.com/browns.png",
      date: "Sunday @ 1:00pm",
    },
    {
      id: "4",
      week: "5",
      team1: "Houston Texans",
      team2: "Baltimore Ravens",
      team1Spread: 6.5,
      team2Spread: -6.5,
      team1Url: "https://wagerwire-webassets.s3.amazonaws.com/texans.png",
      team2Url: "https://wagerwire-webassets.s3.amazonaws.com/ravens.png",
      date: "Sunday @ 1:00pm",
    },
    {
      id: "5",
      week: "5",
      team1: "Tampa Bay Buccaneers",
      team2: "Washington Commanders",
      team1Spread: 6.5,
      team2Spread: -6.5,
      team1Url: "https://wagerwire-webassets.s3.amazonaws.com/buccaneers.png",
      team2Url: "https://wagerwire-webassets.s3.amazonaws.com/redskins.png",
      date: "Sunday @ 1:00pm",
    },
    {
      id: "6",
      week: "5",
      team1: "Jacksonville Jaguars",
      team2: "Indianapolis Colts",
      team1Spread: -6.5,
      team2Spread: 6.5,
      team1Url: "https://wagerwire-webassets.s3.amazonaws.com/jaguars.png",
      team2Url: "https://wagerwire-webassets.s3.amazonaws.com/colts.png",
      date: "Sunday @ 1:00pm",
    },
    {
      id: "7",
      week: "5",
      team1: "San Francisco 49ers",
      team2: "Pittsburgh Steelers",
      team1Spread: -8.5,
      team2Spread: 8.5,
      team1Url: "https://wagerwire-webassets.s3.amazonaws.com/49ers.png",
      team2Url: "https://wagerwire-webassets.s3.amazonaws.com/steelers.png",
      date: "Sunday @ 1:00pm",
    },
  ],
}